[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[dependencies]
python = "^3.7"
requests = "^2.24.0"
lxml = "^4.5.2"

[dev-dependencies]
pytest = "^5.2"
flake8 = "^3.8.3"
flake8-print = "^3.1.4"
flake8-docstrings = "^1.5.0"
